INSERT INTO HOUSE_DOMAIN (ADDRESS) 
VALUES 
('123 Road'), 
('13 Street');

INSERT INTO CAT_DOMAIN (AGE, NAME, SPEECH_VOLUME, MY_HOUSE_ID) 
VALUES 
(10, 'TESLA', 11, 1), 
(11, 'WHISKERS', 7, 1),
(7, 'FELIX', 8, 2), 
(15, 'JACK', 1, 2);
